##### This dataset contains Real Estate listings in the US broken by State and zip code.
##### Data was collected via web scraping using python libraries.
##### We are going to use such Python libraries as NumPy, Pandas, Matplotlib and Seaborn, Scikit-learn

In [297]:
# import libraries

import numpy as np
import pandas as pd 

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [298]:
# import the csv file into Pandas data frame object using pd.read_csv function
data = pd.read_csv("realtor-data.csv")

#### First step: Look at the data, which columns we have, data types of columns, null values or suspiciosly unreasonable datas

In [299]:
data.head(10)

status     price  bed  bath  acre_lot  \
0  for_sale  105000.0  3.0   2.0      0.12   
1  for_sale   80000.0  4.0   2.0      0.08   
2  for_sale   67000.0  2.0   1.0      0.15   
3  for_sale  145000.0  4.0   2.0      0.10   
4  for_sale   65000.0  6.0   2.0      0.05   
5  for_sale  179000.0  4.0   3.0      0.46   
6  for_sale   50000.0  3.0   1.0      0.20   
7  for_sale   71600.0  3.0   2.0      0.08   
8  for_sale  100000.0  2.0   1.0      0.09   
9  for_sale  300000.0  5.0   3.0      7.46   

                                        full_address  \
0  Sector Yahuecas Titulo # V84, Adjuntas, PR, 00601   
1            Km 78 9 Carr # 135, Adjuntas, PR, 00601   
2            556G 556-G 16 St, Juana Diaz, PR, 00795   
3  R5 Comunidad El Paraso Calle De Oro R-5 Ponce,...   
4                    14 Navarro, Mayaguez, PR, 00680   
5  Bo Calabazas San Sebastian, San Sebastian, PR,...   
6                        49.1 140, Ciales, PR, 00639   
7                          3467 St, Ponce, PR, 00731   
8                  230 Rio De Vida, Ponce, PR, 00730   
9  Pr 120 Bo Maravilla Sur K M # 335, Las Marias,...   

                                          street           city        state  \
0                   Sector Yahuecas Titulo # V84       Adjuntas  Puerto Rico   
1                             Km 78 9 Carr # 135       Adjuntas  Puerto Rico   
2                               556G 556-G 16 St     Juana Diaz  Puerto Rico   
3  R5 Comunidad El Paraso Calle De Oro R-5 Ponce          Ponce  Puerto Rico   
4                                     14 Navarro       Mayaguez  Puerto Rico   
5                     Bo Calabazas San Sebastian  San Sebastian  Puerto Rico   
6                                       49.1 140         Ciales  Puerto Rico   
7                                        3467 St          Ponce  Puerto Rico   
8                                230 Rio De Vida          Ponce  Puerto Rico   
9              Pr 120 Bo Maravilla Sur K M # 335     Las Marias  Puerto Rico   

   zip_code  house_size sold_date  
0     601.0       920.0       NaN  
1     601.0      1527.0       NaN  
2     795.0       748.0       NaN  
3     731.0      1800.0       NaN  
4     680.0         NaN       NaN  
5     612.0      2520.0       NaN  
6     639.0      2040.0       NaN  
7     731.0      1050.0       NaN  
8     730.0      1092.0       NaN  
9     670.0      5403.0       NaN

In [300]:
data.isna()

status  price    bed   bath  acre_lot  full_address  street   city  \
0        False  False  False  False     False         False   False  False   
1        False  False  False  False     False         False   False  False   
2        False  False  False  False     False         False   False  False   
3        False  False  False  False     False         False   False  False   
4        False  False  False  False     False         False   False  False   
...        ...    ...    ...    ...       ...           ...     ...    ...   
923154   False  False  False  False     False         False   False  False   
923155   False  False  False  False     False         False   False  False   
923156   False  False  False  False     False         False   False  False   
923157   False  False  False  False     False         False   False  False   
923158   False  False   True   True     False         False   False  False   

        state  zip_code  house_size  sold_date  
0       False     False       False       True  
1       False     False       False       True  
2       False     False       False       True  
3       False     False       False       True  
4       False     False        True       True  
...       ...       ...         ...        ...  
923154  False     False       False      False  
923155  False     False       False      False  
923156  False     False       False       True  
923157  False     False       False      False  
923158  False     False       False       True  

[923159 rows x 12 columns]

In [301]:
data.shape #923159 rows and 12 columns

# our dependent column - price, 11 others - independent which are going to be used to predict real estate price

(923159, 12)

In [302]:
# look at the colunmn types and quantity of non-null values
data.info()

# can see that house_size, sold_date and acre_lot have the biggest quantity of missed values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 923159 entries, 0 to 923158
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   status        923159 non-null  object 
 1   price         923088 non-null  float64
 2   bed           791456 non-null  float64
 3   bath          807967 non-null  float64
 4   acre_lot      649536 non-null  float64
 5   full_address  923159 non-null  object 
 6   street        921021 non-null  object 
 7   city          923085 non-null  object 
 8   state         923159 non-null  object 
 9   zip_code      922954 non-null  float64
 10  house_size    625316 non-null  float64
 11  sold_date     456396 non-null  object 
dtypes: float64(6), object(6)
memory usage: 84.5+ MB


In [303]:
data.isna().sum()

# should come up with some decision how to deal with null values

status               0
price               71
bed             131703
bath            115192
acre_lot        273623
full_address         0
street            2138
city                74
state                0
zip_code           205
house_size      297843
sold_date       466763
dtype: int64

In [304]:
# some descriptive statisctics, using again pandas function

data.describe()

# max amound of beds - 123 and max amoung of bath - 198 - hmm, maybe outliears? 
#probably farther visualisation can help

price            bed           bath       acre_lot  \
count  9.230880e+05  791456.000000  807967.000000  649536.000000   
mean   8.841225e+05       3.330352       2.488164      17.075888   
std    2.623745e+06       2.070402       1.940057     962.322866   
min    0.000000e+00       1.000000       1.000000       0.000000   
25%    2.690000e+05       2.000000       1.000000       0.110000   
50%    4.750000e+05       3.000000       2.000000       0.290000   
75%    8.399000e+05       4.000000       3.000000       1.150000   
max    8.750000e+08     123.000000     198.000000  100000.000000   

            zip_code    house_size  
count  922954.000000  6.253160e+05  
mean     6590.061523  2.141644e+03  
std      3818.208203  3.035327e+03  
min       601.000000  1.000000e+02  
25%      2919.000000  1.130000e+03  
50%      7004.000000  1.651000e+03  
75%     10001.000000  2.499000e+03  
max     99999.000000  1.450112e+06

In [305]:
data.columns

Index(['status', 'price', 'bed', 'bath', 'acre_lot', 'full_address', 'street',
       'city', 'state', 'zip_code', 'house_size', 'sold_date'],
      dtype='object')

In [306]:
data['state'].unique()

array(['Puerto Rico', 'Virgin Islands', 'Massachusetts', 'Connecticut',
       'New Hampshire', 'Vermont', 'New Jersey', 'New York',
       'South Carolina', 'Tennessee', 'Rhode Island', 'Virginia',
       'Wyoming', 'Maine', 'Georgia', 'Pennsylvania', 'West Virginia',
       'Delaware'], dtype=object)

In [307]:
data['city'].unique().size
# wow, 2543 unique cities - a lot

2543

In [308]:
data['bed'].unique()
# after getting rid of nan values, it's nice to have a look the mean and mediand of number of beds,baths,sizes

array([  3.,   4.,   2.,   6.,   5.,   1.,   9.,  nan,   7.,   8.,  12.,
        13.,  10.,  11.,  33.,  24.,  28.,  14.,  18.,  20.,  16.,  15.,
        19.,  17.,  40.,  21.,  86.,  31.,  27.,  42.,  60.,  22.,  32.,
        99.,  49.,  29.,  30.,  23.,  46.,  36.,  68., 123.,  25.,  47.])

In [309]:
data['bath'].unique()

array([  2.,   1.,   3.,   5.,   4.,   7.,   6.,  nan,   8.,   9.,  10.,
        12.,  13.,  35.,  11.,  16.,  15.,  18.,  20.,  14.,  36.,  25.,
        17.,  19.,  56.,  42.,  51.,  28., 198.,  22.,  33.,  27.,  30.,
        29.,  24.,  46.,  21., 123.,  39.,  43.])

In [310]:
data['zip_code'].unique()

array([  601.,   795.,   731., ..., 12601., 12575., 12520.])

In [311]:
data['zip_code'].unique().size

3192

In [312]:
data['status'].unique()

array(['for_sale', 'ready_to_build'], dtype=object)

### Deal with NULL values
#### First method of dropping na - simply use Pandas function

In [313]:
data_cleaned_1 = data.dropna()

data_cleaned_1 = data_cleaned_1.reset_index()

data_cleaned_1.head()

index    status     price  bed  bath  acre_lot  \
0    829  for_sale  110000.0  7.0   3.0      0.09   
1   3380  for_sale  110000.0  7.0   3.0      0.09   
2   5083  for_sale  110000.0  7.0   3.0      0.09   
3   5387  for_sale  110000.0  7.0   3.0      0.09   
4   9053  for_sale  110000.0  7.0   3.0      0.09   

                         full_address           street    city        state  \
0  B-2 Monte Elena, Dorado, PR, 00949  B-2 Monte Elena  Dorado  Puerto Rico   
1  B-2 Monte Elena, Dorado, PR, 00949  B-2 Monte Elena  Dorado  Puerto Rico   
2  B-2 Monte Elena, Dorado, PR, 00949  B-2 Monte Elena  Dorado  Puerto Rico   
3  B-2 Monte Elena, Dorado, PR, 00949  B-2 Monte Elena  Dorado  Puerto Rico   
4  B-2 Monte Elena, Dorado, PR, 00949  B-2 Monte Elena  Dorado  Puerto Rico   

   zip_code  house_size   sold_date  
0     949.0      1192.0  2019-06-28  
1     949.0      1192.0  2019-06-28  
2     949.0      1192.0  2019-06-28  
3     949.0      1192.0  2019-06-28  
4     949.0      1192.0  2019-06-28

In [314]:
data_cleaned_1.shape

# as we can see, using the first method of deleting na we simple deleted more than half of our dataset
# it can be dangerous and may lead to underirable results

(231987, 13)

#### Second method of dropping na - have a look of importance of the columns and quantity of null values, delete unnecessary and aftet drop na rows

In [315]:
data.isna().sum()

status               0
price               71
bed             131703
bath            115192
acre_lot        273623
full_address         0
street            2138
city                74
state                0
zip_code           205
house_size      297843
sold_date       466763
dtype: int64

In [316]:
data_cleaned_2 = data
data_cleaned_2.drop(['sold_date','acre_lot'], inplace=True, axis=1)

In [317]:
data_cleaned_2.head()

status     price  bed  bath  \
0  for_sale  105000.0  3.0   2.0   
1  for_sale   80000.0  4.0   2.0   
2  for_sale   67000.0  2.0   1.0   
3  for_sale  145000.0  4.0   2.0   
4  for_sale   65000.0  6.0   2.0   

                                        full_address  \
0  Sector Yahuecas Titulo # V84, Adjuntas, PR, 00601   
1            Km 78 9 Carr # 135, Adjuntas, PR, 00601   
2            556G 556-G 16 St, Juana Diaz, PR, 00795   
3  R5 Comunidad El Paraso Calle De Oro R-5 Ponce,...   
4                    14 Navarro, Mayaguez, PR, 00680   

                                          street        city        state  \
0                   Sector Yahuecas Titulo # V84    Adjuntas  Puerto Rico   
1                             Km 78 9 Carr # 135    Adjuntas  Puerto Rico   
2                               556G 556-G 16 St  Juana Diaz  Puerto Rico   
3  R5 Comunidad El Paraso Calle De Oro R-5 Ponce       Ponce  Puerto Rico   
4                                     14 Navarro    Mayaguez  Puerto Rico   

   zip_code  house_size  
0     601.0       920.0  
1     601.0      1527.0  
2     795.0       748.0  
3     731.0      1800.0  
4     680.0         NaN

In [318]:
data_cleaned_2 = data_cleaned_2.dropna()

data_cleaned_2.shape

# (600684, 10) - perfect! as we can see, in this case we delete two unncessary columns and then apply pandas
# function dropna - and it's works definitely better - we saved almost 300000 rows of data - approxximetly 1/3 
# of our original data

(600684, 10)

In [319]:
# I think status, full_address,street,index,sold_date now for us don't make so much sense, we can also drop it

data_cleaned_2.drop(['full_address','street','zip_code'], inplace=True, axis=1)

/Users/nikita_voitishyn/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py:4906: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [320]:
data_cleaned_2.head()

# now we are ready to create some visualisations, probably delete out outliears and after we can move on to the
# next step - machine learning step

status     price  bed  bath           city        state  house_size
0  for_sale  105000.0  3.0   2.0       Adjuntas  Puerto Rico       920.0
1  for_sale   80000.0  4.0   2.0       Adjuntas  Puerto Rico      1527.0
2  for_sale   67000.0  2.0   1.0     Juana Diaz  Puerto Rico       748.0
3  for_sale  145000.0  4.0   2.0          Ponce  Puerto Rico      1800.0
5  for_sale  179000.0  4.0   3.0  San Sebastian  Puerto Rico      2520.0

In [321]:
data_cleaned_2['status'].unique()

array(['for_sale'], dtype=object)

#### Will create linear regression using sklearn library

In [322]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [323]:
data_cleaned_2.head()

status     price  bed  bath           city        state  house_size
0  for_sale  105000.0  3.0   2.0       Adjuntas  Puerto Rico       920.0
1  for_sale   80000.0  4.0   2.0       Adjuntas  Puerto Rico      1527.0
2  for_sale   67000.0  2.0   1.0     Juana Diaz  Puerto Rico       748.0
3  for_sale  145000.0  4.0   2.0          Ponce  Puerto Rico      1800.0
5  for_sale  179000.0  4.0   3.0  San Sebastian  Puerto Rico      2520.0

In [356]:
X = data_cleaned_2[['house_size']]
Y = data_cleaned_2['price']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [325]:
X_train

house_size
903726      1023.0
298533      2203.0
362901      1378.0
653919      1314.0
657222      2272.0
...            ...
139006      2725.0
323208      7465.0
467648       800.0
161825      1115.0
151329      1266.0

[480547 rows x 1 columns]

In [326]:
first_model = LinearRegression()
first_model.fit(X_train, Y_train)

LinearRegression()

In [327]:
first_model.predict(X_test)

array([ 906034.35630123,  910838.95950038,  843874.80241226, ...,
        893422.27290347, 1301212.96943115,  826758.40351529])

In [328]:
first_model.score(X_test,Y_test)

0.07713678970023585

In [329]:
X = data_cleaned_2[['house_size','bath','bed']]
Y = data_cleaned_2['price']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [330]:
first_model_1 = LinearRegression()
first_model_1.fit(X_train, Y_train)

LinearRegression()

In [331]:
first_model_1.coef_

array([ 8.47515022e+01,  4.08754053e+05, -1.22107486e+05])

In [332]:
# as we can see we adder two more paremeteres and use multiple linear regression
# in this case our model of perforamce became much better
first_model_1.score(X_test,Y_test)

0.1599295164718535

#### Lets make encoding of categorical feature: dummy encoding

In [333]:
data_cleaned_2 = pd.get_dummies(data_cleaned_2,columns=['status'],prefix='status')

In [334]:
data_cleaned_2.head(10)

price  bed  bath           city        state  house_size  \
0   105000.0  3.0   2.0       Adjuntas  Puerto Rico       920.0   
1    80000.0  4.0   2.0       Adjuntas  Puerto Rico      1527.0   
2    67000.0  2.0   1.0     Juana Diaz  Puerto Rico       748.0   
3   145000.0  4.0   2.0          Ponce  Puerto Rico      1800.0   
5   179000.0  4.0   3.0  San Sebastian  Puerto Rico      2520.0   
6    50000.0  3.0   1.0         Ciales  Puerto Rico      2040.0   
7    71600.0  3.0   2.0          Ponce  Puerto Rico      1050.0   
8   100000.0  2.0   1.0          Ponce  Puerto Rico      1092.0   
9   300000.0  5.0   3.0     Las Marias  Puerto Rico      5403.0   
10   89000.0  3.0   2.0        Isabela  Puerto Rico      1106.0   

    status_for_sale  
0                 1  
1                 1  
2                 1  
3                 1  
5                 1  
6                 1  
7                 1  
8                 1  
9                 1  
10                1

In [335]:
 data_cleaned_2 = pd.get_dummies(data_cleaned_2,columns=['state'],prefix='state')

In [336]:
data_cleaned_2.head()

price  bed  bath           city  house_size  status_for_sale  \
0  105000.0  3.0   2.0       Adjuntas       920.0                1   
1   80000.0  4.0   2.0       Adjuntas      1527.0                1   
2   67000.0  2.0   1.0     Juana Diaz       748.0                1   
3  145000.0  4.0   2.0          Ponce      1800.0                1   
5  179000.0  4.0   3.0  San Sebastian      2520.0                1   

   state_Connecticut  state_Delaware  state_Georgia  state_Maine  ...  \
0                  0               0              0            0  ...   
1                  0               0              0            0  ...   
2                  0               0              0            0  ...   
3                  0               0              0            0  ...   
5                  0               0              0            0  ...   

   state_New Hampshire  state_New Jersey  state_New York  state_Pennsylvania  \
0                    0                 0               0                   0   
1                    0                 0               0                   0   
2                    0                 0               0                   0   
3                    0                 0               0                   0   
5                    0                 0               0                   0   

   state_Puerto Rico  state_Rhode Island  state_Vermont  state_Virgin Islands  \
0                  1                   0              0                     0   
1                  1                   0              0                     0   
2                  1                   0              0                     0   
3                  1                   0              0                     0   
5                  1                   0              0                     0   

   state_West Virginia  state_Wyoming  
0                    0              0  
1                    0              0  
2                    0              0  
3                    0              0  
5                    0              0  

[5 rows x 21 columns]

In [337]:
data_cleaned_2.drop(['city'], inplace=True, axis=1)

In [338]:
data_cleaned_2.columns

Index(['price', 'bed', 'bath', 'house_size', 'status_for_sale',
       'state_Connecticut', 'state_Delaware', 'state_Georgia', 'state_Maine',
       'state_Massachusetts', 'state_New Hampshire', 'state_New Jersey',
       'state_New York', 'state_Pennsylvania', 'state_Puerto Rico',
       'state_Rhode Island', 'state_Vermont', 'state_Virgin Islands',
       'state_West Virginia', 'state_Wyoming'],
      dtype='object')

In [354]:
data_cleaned_2

price  bed  bath  house_size  status_for_sale  state_Connecticut  \
0       105000.0  3.0   2.0       920.0                1                  0   
1        80000.0  4.0   2.0      1527.0                1                  0   
2        67000.0  2.0   1.0       748.0                1                  0   
3       145000.0  4.0   2.0      1800.0                1                  0   
5       179000.0  4.0   3.0      2520.0                1                  0   
...          ...  ...   ...         ...              ...                ...   
923153  825000.0  5.0   5.0      4522.0                1                  0   
923154  445000.0  1.0   2.0      1052.0                1                  0   
923155  418000.0  4.0   2.0      1650.0                1                  0   
923156  469000.0  4.0   2.0      2123.0                1                  0   
923157  825000.0  5.0   5.0      3775.0                1                  0   

        state_Delaware  state_Georgia  state_Maine  state_Massachusetts  \
0                    0              0            0                    0   
1                    0              0            0                    0   
2                    0              0            0                    0   
3                    0              0            0                    0   
5                    0              0            0                    0   
...                ...            ...          ...                  ...   
923153               0              0            0                    0   
923154               0              0            0                    0   
923155               0              0            0                    0   
923156               0              0            0                    0   
923157               0              0            0                    0   

        state_New Hampshire  state_New Jersey  state_New York  \
0                         0                 0               0   
1                         0                 0               0   
2                         0                 0               0   
3                         0                 0               0   
5                         0                 0               0   
...                     ...               ...             ...   
923153                    0                 0               1   
923154                    0                 0               1   
923155                    0                 0               1   
923156                    0                 0               1   
923157                    0                 0               1   

        state_Pennsylvania  state_Puerto Rico  state_Rhode Island  \
0                        0                  1                   0   
1                        0                  1                   0   
2                        0                  1                   0   
3                        0                  1                   0   
5                        0                  1                   0   
...                    ...                ...                 ...   
923153                   0                  0                   0   
923154                   0                  0                   0   
923155                   0                  0                   0   
923156                   0                  0                   0   
923157                   0                  0                   0   

        state_Vermont  state_Virgin Islands  state_West Virginia  \
0                   0                     0                    0   
1                   0                     0                    0   
2                   0                     0                    0   
3                   0                     0                    0   
5                   0                     0                    0   
...               ...                   ...                  ...   
923153              0                     0                    0   
923154 

In [357]:
X = data_cleaned_2[[ 'bed', 'bath', 'house_size', 'status_for_sale',
       'state_Connecticut', 'state_Delaware', 'state_Georgia', 'state_Maine',
       'state_Massachusetts', 'state_New Hampshire', 'state_New Jersey',
       'state_New York', 'state_Pennsylvania', 'state_Puerto Rico',
       'state_Rhode Island', 'state_Vermont', 'state_Virgin Islands',
       'state_West Virginia', 'state_Wyoming']]

In [358]:
Y = data_cleaned_2['price']

In [359]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [360]:
first_model_2 = LinearRegression()
first_model_2.fit(X_train, Y_train)

LinearRegression()

In [362]:
first_model_2.score(X_test,Y_test)
# 7% more accuracy than previous model

0.23803965378638137

In [380]:
scaler = StandardScaler().fit(X)

In [383]:
X_std = scaler.transform(X)

In [384]:
X_std

array([[-0.16270122, -0.25893728, -0.41354619, ..., -0.02874731,
        -0.0022348 , -0.0022348 ],
       [ 0.31222634, -0.25893728, -0.20742314, ..., -0.02874731,
        -0.0022348 , -0.0022348 ],
       [-0.63762877, -0.75044003, -0.47195338, ..., -0.02874731,
        -0.0022348 , -0.0022348 ],
       ...,
       [ 0.31222634, -0.25893728, -0.1656552 , ..., -0.02874731,
        -0.0022348 , -0.0022348 ],
       [ 0.31222634, -0.25893728, -0.00503543, ..., -0.02874731,
        -0.0022348 , -0.0022348 ],
       [ 0.78715389,  1.21557095,  0.55594527, ..., -0.02874731,
        -0.0022348 , -0.0022348 ]])

In [392]:
X_train, X_test, Y_train, Y_test = train_test_split(X_std, Y, test_size=0.2, random_state=42)

first_model_3 = LinearRegression()
first_model_3.fit(X_train, Y_train)

LinearRegression()

In [394]:
first_model_3.score(X_test,Y_test)

# as we can see our accuracy remains still very low and not enough to use in a real life 

0.23812130811517984